// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: env.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Main entity: environment configuration
type EnvConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                                     // Unique name of the environment
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                                                                       // Description
	Variables     map[string]string      `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Environment variables
	Services      []string               `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`                                                                             // Names of services (e.g., postgres, redis, app)
	RawCompose    string                 `protobuf:"bytes,5,opt,name=raw_compose,json=rawCompose,proto3" json:"raw_compose,omitempty"`                                                       // Docker-compose text (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvConfig) Reset() {
	*x = EnvConfig{}
	mi := &file_env_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvConfig) ProtoMessage() {}

func (x *EnvConfig) ProtoReflect() protoreflect.Message {
	mi := &file_env_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvConfig.ProtoReflect.Descriptor instead.
func (*EnvConfig) Descriptor() ([]byte, []int) {
	return file_env_proto_rawDescGZIP(), []int{0}
}

func (x *EnvConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EnvConfig) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *EnvConfig) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *EnvConfig) GetRawCompose() string {
	if x != nil {
		return x.RawCompose
	}
	return ""
}

// Request by environment name
type EnvRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvRequest) Reset() {
	*x = EnvRequest{}
	mi := &file_env_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvRequest) ProtoMessage() {}

func (x *EnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_env_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvRequest.ProtoReflect.Descriptor instead.
func (*EnvRequest) Descriptor() ([]byte, []int) {
	return file_env_proto_rawDescGZIP(), []int{1}
}

func (x *EnvRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// List of all environments
type EnvList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*EnvConfig           `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvList) Reset() {
	*x = EnvList{}
	mi := &file_env_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvList) ProtoMessage() {}

func (x *EnvList) ProtoReflect() protoreflect.Message {
	mi := &file_env_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvList.ProtoReflect.Descriptor instead.
func (*EnvList) Descriptor() ([]byte, []int) {
	return file_env_proto_rawDescGZIP(), []int{2}
}

func (x *EnvList) GetConfigs() []*EnvConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

// Empty request
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_env_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_env_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_env_proto_rawDescGZIP(), []int{3}
}

var File_env_proto protoreflect.FileDescriptor

const file_env_proto_rawDesc = "" +
	"\n" +
	"\tenv.proto\x12\x03env\x1a\x1cgoogle/api/annotations.proto\"\xf9\x01\n" +
	"\tEnvConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12;\n" +
	"\tvariables\x18\x03 \x03(\v2\x1d.env.EnvConfig.VariablesEntryR\tvariables\x12\x1a\n" +
	"\bservices\x18\x04 \x03(\tR\bservices\x12\x1f\n" +
	"\vraw_compose\x18\x05 \x01(\tR\n" +
	"rawCompose\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\" \n" +
	"\n" +
	"EnvRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"3\n" +
	"\aEnvList\x12(\n" +
	"\aconfigs\x18\x01 \x03(\v2\x0e.env.EnvConfigR\aconfigs\"\a\n" +
	"\x05Empty2\xa4\x02\n" +
	"\n" +
	"EnvService\x12H\n" +
	"\fGetEnvConfig\x12\x0f.env.EnvRequest\x1a\x0e.env.EnvConfig\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/envs/{name}\x12<\n" +
	"\x0eListEnvConfigs\x12\n" +
	".env.Empty\x1a\f.env.EnvList\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/envs\x12E\n" +
	"\x0eApplyEnvConfig\x12\x0e.env.EnvConfig\x1a\x0e.env.EnvConfig\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/envs\x12G\n" +
	"\x0fDeleteEnvConfig\x12\x0f.env.EnvRequest\x1a\n" +
	".env.Empty\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/v1/envs/{name}B.Z,github.com/ConfigMagic/dummy/server/pb/pb;pbb\x06proto3"

var (
	file_env_proto_rawDescOnce sync.Once
	file_env_proto_rawDescData []byte
)

func file_env_proto_rawDescGZIP() []byte {
	file_env_proto_rawDescOnce.Do(func() {
		file_env_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_env_proto_rawDesc), len(file_env_proto_rawDesc)))
	})
	return file_env_proto_rawDescData
}

var file_env_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_env_proto_goTypes = []any{
	(*EnvConfig)(nil),  // 0: env.EnvConfig
	(*EnvRequest)(nil), // 1: env.EnvRequest
	(*EnvList)(nil),    // 2: env.EnvList
	(*Empty)(nil),      // 3: env.Empty
	nil,                // 4: env.EnvConfig.VariablesEntry
}
var file_env_proto_depIdxs = []int32{
	4, // 0: env.EnvConfig.variables:type_name -> env.EnvConfig.VariablesEntry
	0, // 1: env.EnvList.configs:type_name -> env.EnvConfig
	1, // 2: env.EnvService.GetEnvConfig:input_type -> env.EnvRequest
	3, // 3: env.EnvService.ListEnvConfigs:input_type -> env.Empty
	0, // 4: env.EnvService.ApplyEnvConfig:input_type -> env.EnvConfig
	1, // 5: env.EnvService.DeleteEnvConfig:input_type -> env.EnvRequest
	0, // 6: env.EnvService.GetEnvConfig:output_type -> env.EnvConfig
	2, // 7: env.EnvService.ListEnvConfigs:output_type -> env.EnvList
	0, // 8: env.EnvService.ApplyEnvConfig:output_type -> env.EnvConfig
	3, // 9: env.EnvService.DeleteEnvConfig:output_type -> env.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_env_proto_init() }
func file_env_proto_init() {
	if File_env_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_env_proto_rawDesc), len(file_env_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_env_proto_goTypes,
		DependencyIndexes: file_env_proto_depIdxs,
		MessageInfos:      file_env_proto_msgTypes,
	}.Build()
	File_env_proto = out.File
	file_env_proto_goTypes = nil
	file_env_proto_depIdxs = nil
}
