services:
  server:
    build:
      context: ../../server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - DUMMY_SERVER_URL=http://localhost:8080
      - LOCAL_FILES=./local_data
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=dummy
      - MONGO_CONFIGS_COLLECTION=configs
    command: ["/app/server"]
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
